In [116]:
import pandas as pd
file = open('testfile.txt','r') 
cri_data = file.read().split(" \n")

In [117]:
cri_test = pd.read_csv("criminal_test.csv")
columns = cri_test.columns
columns=columns[:-4].append(columns[-1:])
cri_test.head(5)

,PERID,IFATHER,NRCH17_2,IRHHSIZ2,IIHHSIZ2,IRKI17_2,IIKI17_2,IRHH65_2,IIHH65_2,PRXRETRY,...,POVERTY3,TOOLONG,TROUBUND,PDEN10,COUTYP2,MAIIN102,AIIND102,ANALWT_C,VESTR,VEREP
0,66583679,4,0,4,1,2,1,1,1,99,...,2,2,2,1,1,2,2,16346.795400,40020,1
1,35494679,4,0,4,1,1,1,1,1,99,...,3,2,2,1,1,2,2,3008.863906,40044,2
2,79424679,2,0,3,1,2,1,1,1,99,...,1,2,2,2,2,2,2,266.952503,40040,2
3,11744679,4,0,6,1,2,1,1,1,99,...,3,2,2,1,1,2,2,5386.928199,40017,1
4,31554679,1,0,4,1,3,1,1,1,99,...,3,2,1,1,1,2,2,173.489895,40017,1

In [118]:
columns

Index([u'PERID', u'IFATHER', u'NRCH17_2', u'IRHHSIZ2', u'IIHHSIZ2',
       u'IRKI17_2', u'IIKI17_2', u'IRHH65_2', u'IIHH65_2', u'PRXRETRY',
       u'PRXYDATA', u'MEDICARE', u'CAIDCHIP', u'CHAMPUS', u'PRVHLTIN',
       u'GRPHLTIN', u'HLTINNOS', u'HLCNOTYR', u'HLCNOTMO', u'HLCLAST',
       u'HLLOSRSN', u'HLNVCOST', u'HLNVOFFR', u'HLNVREF', u'HLNVNEED',
       u'HLNVSOR', u'IRMCDCHP', u'IIMCDCHP', u'IRMEDICR', u'IIMEDICR',
       u'IRCHMPUS', u'IICHMPUS', u'IRPRVHLT', u'IIPRVHLT', u'IROTHHLT',
       u'IIOTHHLT', u'HLCALLFG', u'HLCALL99', u'ANYHLTI2', u'IRINSUR4',
       u'IIINSUR4', u'OTHINS', u'CELLNOTCL', u'CELLWRKNG', u'IRFAMSOC',
       u'IIFAMSOC', u'IRFAMSSI', u'IIFAMSSI', u'IRFSTAMP', u'IIFSTAMP',
       u'IRFAMPMT', u'IIFAMPMT', u'IRFAMSVC', u'IIFAMSVC', u'IRWELMOS',
       u'IIWELMOS', u'IRPINC3', u'IRFAMIN3', u'IIPINC3', u'IIFAMIN3',
       u'GOVTPROG', u'POVERTY3', u'TOOLONG', u'TROUBUND', u'PDEN10',
       u'COUTYP2', u'MAIIN102', u'VEREP'],
      dtype='object')

In [119]:
def getstri(per):
    pp = ""
    for i in columns:
        if i=="PERID":
            continue
        pp+=str(float(per[i]))
    return pp

In [125]:
result = []
getstri(cri_test.iloc[0])
testlen = len(cri_test)
for i in xrange(testlen):
    tem = (getstri(cri_test.iloc[i])).strip()
    if tem in cri_data:
        result.append([int(cri_test.iloc[i][columns[0]]),1])
    else:
        result.append([int(cri_test.iloc[i][columns[0]]),0])

In [ ]:
for i in xrange(10):
    tem = (getstri(cri_test.iloc[i])).strip()
    print tem," len:",len(tem)
    if tem in cri_data:
        result[int(cri_test.iloc[i][columns[0]])]=1
    else:
        result[int(cri_test.iloc[i][columns[0]])]=0

In [133]:
col = ['PERID','Criminal']
resdf = pd.DataFrame(result)
resdf.columns=col

In [135]:
resdf.to_csv("criminalRcsv.csv",index=False)